package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;
import org.ufida.UFIDAU9ISVRCVICreateRCVSRV;

/**
 * This class was generated by Apache CXF 3.4.0
 * 2020-11-04T17:17:31.613+08:00
 * Generated source version: 3.4.0
 *
 */
@WebServiceClient(name = "CreateRCVSRVStub",
                  wsdlLocation = "http://localhost/U9/services/UFIDA.U9.ISV.RCV.ICreateRCVSRV.svc?wsdl",
                  targetNamespace = "http://tempuri.org/")
public class CreateRCVSRVStub extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "CreateRCVSRVStub");
    public final static QName BasicHttpBindingUFIDAU9ISVRCVICreateRCVSRV = new QName("http://tempuri.org/", "BasicHttpBinding_UFIDA.U9.ISV.RCV.ICreateRCVSRV");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost/U9/services/UFIDA.U9.ISV.RCV.ICreateRCVSRV.svc?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CreateRCVSRVStub.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost/U9/services/UFIDA.U9.ISV.RCV.ICreateRCVSRV.svc?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CreateRCVSRVStub(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CreateRCVSRVStub(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CreateRCVSRVStub() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CreateRCVSRVStub(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CreateRCVSRVStub(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CreateRCVSRVStub(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns UFIDAU9ISVRCVICreateRCVSRV
     */
    @WebEndpoint(name = "BasicHttpBinding_UFIDA.U9.ISV.RCV.ICreateRCVSRV")
    public UFIDAU9ISVRCVICreateRCVSRV getBasicHttpBindingUFIDAU9ISVRCVICreateRCVSRV() {
        return super.getPort(BasicHttpBindingUFIDAU9ISVRCVICreateRCVSRV, UFIDAU9ISVRCVICreateRCVSRV.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UFIDAU9ISVRCVICreateRCVSRV
     */
    @WebEndpoint(name = "BasicHttpBinding_UFIDA.U9.ISV.RCV.ICreateRCVSRV")
    public UFIDAU9ISVRCVICreateRCVSRV getBasicHttpBindingUFIDAU9ISVRCVICreateRCVSRV(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingUFIDAU9ISVRCVICreateRCVSRV, UFIDAU9ISVRCVICreateRCVSRV.class, features);
    }

}
