package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;
import org.ufida.UFIDAU9SMShipIQueryShipByIDs;

/**
 * This class was generated by Apache CXF 3.4.0
 * 2020-11-04T17:01:19.703+08:00
 * Generated source version: 3.4.0
 *
 */
@WebServiceClient(name = "QueryShipByIDsStub",
                  wsdlLocation = "http://localhost/U9/services/UFIDA.U9.SM.Ship.IQueryShipByIDs.svc?wsdl",
                  targetNamespace = "http://tempuri.org/")
public class QueryShipByIDsStub extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "QueryShipByIDsStub");
    public final static QName BasicHttpBindingUFIDAU9SMShipIQueryShipByIDs = new QName("http://tempuri.org/", "BasicHttpBinding_UFIDA.U9.SM.Ship.IQueryShipByIDs");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost/U9/services/UFIDA.U9.SM.Ship.IQueryShipByIDs.svc?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(QueryShipByIDsStub.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost/U9/services/UFIDA.U9.SM.Ship.IQueryShipByIDs.svc?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public QueryShipByIDsStub(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public QueryShipByIDsStub(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QueryShipByIDsStub() {
        super(WSDL_LOCATION, SERVICE);
    }

    public QueryShipByIDsStub(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public QueryShipByIDsStub(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public QueryShipByIDsStub(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns UFIDAU9SMShipIQueryShipByIDs
     */
    @WebEndpoint(name = "BasicHttpBinding_UFIDA.U9.SM.Ship.IQueryShipByIDs")
    public UFIDAU9SMShipIQueryShipByIDs getBasicHttpBindingUFIDAU9SMShipIQueryShipByIDs() {
        return super.getPort(BasicHttpBindingUFIDAU9SMShipIQueryShipByIDs, UFIDAU9SMShipIQueryShipByIDs.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UFIDAU9SMShipIQueryShipByIDs
     */
    @WebEndpoint(name = "BasicHttpBinding_UFIDA.U9.SM.Ship.IQueryShipByIDs")
    public UFIDAU9SMShipIQueryShipByIDs getBasicHttpBindingUFIDAU9SMShipIQueryShipByIDs(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingUFIDAU9SMShipIQueryShipByIDs, UFIDAU9SMShipIQueryShipByIDs.class, features);
    }

}
