package org.ufida;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.0
 * 2020-11-04T17:17:31.588+08:00
 * Generated source version: 3.4.0
 *
 */
@WebService(targetNamespace = "http://www.UFIDA.org", name = "UFIDA.U9.ISV.RCV.ICreateRCVSRV")
@XmlSeeAlso({org.datacontract.schemas._2004._07.ufsoft_ubf_pl.ObjectFactory.class, org.datacontract.schemas._2004._07.ufsoft_ubf_util.ObjectFactory.class, businessentity.business.ubf.ufsoft.ObjectFactory.class, org.datacontract.schemas._2004._07.system.ObjectFactory.class, data.util.ubf.ufsoft.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, pl.ubf.ufsoft.ObjectFactory.class, org.datacontract.schemas._2004._07.ufsoft.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class, ObjectFactory.class, org.datacontract.schemas._2004._07.ufsoft_ubf.ObjectFactory.class, exceptions.ubf.ufsoft.ObjectFactory.class, org.ufida.entitydata.ObjectFactory.class})
public interface UFIDAU9ISVRCVICreateRCVSRV {

    @WebMethod(operationName = "Do", action = "http://www.UFIDA.org/UFIDA.U9.ISV.RCV.ICreateRCVSRV/Do")
    @Action(input = "http://www.UFIDA.org/UFIDA.U9.ISV.RCV.ICreateRCVSRV/Do", output = "http://www.UFIDA.org/UFIDA.U9.ISV.RCV.ICreateRCVSRV/DoResponse", fault = {@FaultAction(className = UFIDAU9ISVRCVICreateRCVSRVDoServiceExceptionFaultFaultMessage.class, value = "http://www.UFIDA.org/UFIDA.U9.ISV.RCV.ICreateRCVSRV/DoServiceExceptionFault"), @FaultAction(className = UFIDAU9ISVRCVICreateRCVSRVDoExceptionBaseFaultFaultMessage.class, value = "http://www.UFIDA.org/UFIDA.U9.ISV.RCV.ICreateRCVSRV/DoExceptionBaseFault"), @FaultAction(className = UFIDAU9ISVRCVICreateRCVSRVDoServiceLostExceptionFaultFaultMessage.class, value = "http://www.UFIDA.org/UFIDA.U9.ISV.RCV.ICreateRCVSRV/DoServiceLostExceptionFault"), @FaultAction(className = UFIDAU9ISVRCVICreateRCVSRVDoExceptionFaultFaultMessage.class, value = "http://www.UFIDA.org/UFIDA.U9.ISV.RCV.ICreateRCVSRV/DoExceptionFault"), @FaultAction(className = UFIDAU9ISVRCVICreateRCVSRVDoServiceExceptionDetailFaultFaultMessage.class, value = "http://www.UFIDA.org/UFIDA.U9.ISV.RCV.ICreateRCVSRV/DoServiceExceptionDetailFault")})
    @RequestWrapper(localName = "Do", targetNamespace = "http://www.UFIDA.org", className = "org.ufida.Do")
    @ResponseWrapper(localName = "DoResponse", targetNamespace = "http://www.UFIDA.org", className = "org.ufida.DoResponse")
    public void _do(

        @WebParam(name = "context", targetNamespace = "http://www.UFIDA.org")
        java.lang.Object context,
        @WebParam(name = "rCVList", targetNamespace = "http://www.UFIDA.org")
        org.ufida.entitydata.ArrayOfUFIDAU9ISVRCVDTOOBAReceivementDTOData rCVList,
        @WebParam(mode = WebParam.Mode.OUT, name = "DoResult", targetNamespace = "http://www.UFIDA.org")
        javax.xml.ws.Holder<org.ufida.entitydata.ArrayOfUFIDAU9PMRcvReceivementData> doResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "outMessages", targetNamespace = "http://www.UFIDA.org")
        javax.xml.ws.Holder<exceptions.ubf.ufsoft.ArrayOfMessageBase> outMessages
    ) throws UFIDAU9ISVRCVICreateRCVSRVDoServiceExceptionFaultFaultMessage, UFIDAU9ISVRCVICreateRCVSRVDoExceptionBaseFaultFaultMessage, UFIDAU9ISVRCVICreateRCVSRVDoServiceLostExceptionFaultFaultMessage, UFIDAU9ISVRCVICreateRCVSRVDoExceptionFaultFaultMessage, UFIDAU9ISVRCVICreateRCVSRVDoServiceExceptionDetailFaultFaultMessage;
}
