
package org.ufida;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.4.0
 * 2020-11-04T17:01:19.631+08:00
 * Generated source version: 3.4.0
 */

@WebFault(name = "Exception", targetNamespace = "http://schemas.datacontract.org/2004/07/System")
public class UFIDAU9SMShipIQueryShipByIDsDoExceptionFaultFaultMessage extends java.lang.Exception {

    private org.datacontract.schemas._2004._07.system.Exception exception;

    public UFIDAU9SMShipIQueryShipByIDsDoExceptionFaultFaultMessage() {
        super();
    }

    public UFIDAU9SMShipIQueryShipByIDsDoExceptionFaultFaultMessage(String message) {
        super(message);
    }

    public UFIDAU9SMShipIQueryShipByIDsDoExceptionFaultFaultMessage(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public UFIDAU9SMShipIQueryShipByIDsDoExceptionFaultFaultMessage(String message, org.datacontract.schemas._2004._07.system.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public UFIDAU9SMShipIQueryShipByIDsDoExceptionFaultFaultMessage(String message, org.datacontract.schemas._2004._07.system.Exception exception, java.lang.Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public org.datacontract.schemas._2004._07.system.Exception getFaultInfo() {
        return this.exception;
    }
}
