
package org.ufida;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.4.0
 * 2020-11-04T17:17:31.566+08:00
 * Generated source version: 3.4.0
 */

@WebFault(name = "ServiceLostException", targetNamespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF.Service")
public class UFIDAU9ISVRCVICreateRCVSRVDoServiceLostExceptionFaultFaultMessage extends java.lang.Exception {

    private org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceLostException serviceLostException;

    public UFIDAU9ISVRCVICreateRCVSRVDoServiceLostExceptionFaultFaultMessage() {
        super();
    }

    public UFIDAU9ISVRCVICreateRCVSRVDoServiceLostExceptionFaultFaultMessage(String message) {
        super(message);
    }

    public UFIDAU9ISVRCVICreateRCVSRVDoServiceLostExceptionFaultFaultMessage(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public UFIDAU9ISVRCVICreateRCVSRVDoServiceLostExceptionFaultFaultMessage(String message, org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceLostException serviceLostException) {
        super(message);
        this.serviceLostException = serviceLostException;
    }

    public UFIDAU9ISVRCVICreateRCVSRVDoServiceLostExceptionFaultFaultMessage(String message, org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceLostException serviceLostException, java.lang.Throwable cause) {
        super(message, cause);
        this.serviceLostException = serviceLostException;
    }

    public org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceLostException getFaultInfo() {
        return this.serviceLostException;
    }
}
