
package org.ufida;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.4.0
 * 2020-11-04T17:01:19.641+08:00
 * Generated source version: 3.4.0
 */

@WebFault(name = "ServiceExceptionDetail", targetNamespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF.Service")
public class UFIDAU9SMShipIQueryShipByIDsDoServiceExceptionDetailFaultFaultMessage extends java.lang.Exception {

    private org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceExceptionDetail serviceExceptionDetail;

    public UFIDAU9SMShipIQueryShipByIDsDoServiceExceptionDetailFaultFaultMessage() {
        super();
    }

    public UFIDAU9SMShipIQueryShipByIDsDoServiceExceptionDetailFaultFaultMessage(String message) {
        super(message);
    }

    public UFIDAU9SMShipIQueryShipByIDsDoServiceExceptionDetailFaultFaultMessage(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public UFIDAU9SMShipIQueryShipByIDsDoServiceExceptionDetailFaultFaultMessage(String message, org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceExceptionDetail serviceExceptionDetail) {
        super(message);
        this.serviceExceptionDetail = serviceExceptionDetail;
    }

    public UFIDAU9SMShipIQueryShipByIDsDoServiceExceptionDetailFaultFaultMessage(String message, org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceExceptionDetail serviceExceptionDetail, java.lang.Throwable cause) {
        super(message, cause);
        this.serviceExceptionDetail = serviceExceptionDetail;
    }

    public org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceExceptionDetail getFaultInfo() {
        return this.serviceExceptionDetail;
    }
}
