
package org.ufida;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.4.0
 * 2020-11-04T17:01:19.469+08:00
 * Generated source version: 3.4.0
 */

@WebFault(name = "ServiceException", targetNamespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF.Service")
public class UFIDAU9SMShipIQueryShipByIDsDoServiceExceptionFaultFaultMessage extends java.lang.Exception {

    private org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceException serviceException;

    public UFIDAU9SMShipIQueryShipByIDsDoServiceExceptionFaultFaultMessage() {
        super();
    }

    public UFIDAU9SMShipIQueryShipByIDsDoServiceExceptionFaultFaultMessage(String message) {
        super(message);
    }

    public UFIDAU9SMShipIQueryShipByIDsDoServiceExceptionFaultFaultMessage(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public UFIDAU9SMShipIQueryShipByIDsDoServiceExceptionFaultFaultMessage(String message, org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceException serviceException) {
        super(message);
        this.serviceException = serviceException;
    }

    public UFIDAU9SMShipIQueryShipByIDsDoServiceExceptionFaultFaultMessage(String message, org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceException serviceException, java.lang.Throwable cause) {
        super(message, cause);
        this.serviceException = serviceException;
    }

    public org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceException getFaultInfo() {
        return this.serviceException;
    }
}
