
package icreateshipsv.org.ufida;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.4.0
 * 2020-11-11T11:45:25.125+08:00
 * Generated source version: 3.4.0
 */

@WebFault(name = "Exception", targetNamespace = "http://schemas.datacontract.org/2004/07/System")
public class UFIDAU9ISVSMICreateShipSVDoExceptionFaultFaultMessage extends Exception {

    private icreateshipsv.org.datacontract.schemas._2004._07.system.Exception exception;

    public UFIDAU9ISVSMICreateShipSVDoExceptionFaultFaultMessage() {
        super();
    }

    public UFIDAU9ISVSMICreateShipSVDoExceptionFaultFaultMessage(String message) {
        super(message);
    }

    public UFIDAU9ISVSMICreateShipSVDoExceptionFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public UFIDAU9ISVSMICreateShipSVDoExceptionFaultFaultMessage(String message, icreateshipsv.org.datacontract.schemas._2004._07.system.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public UFIDAU9ISVSMICreateShipSVDoExceptionFaultFaultMessage(String message, icreateshipsv.org.datacontract.schemas._2004._07.system.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public icreateshipsv.org.datacontract.schemas._2004._07.system.Exception getFaultInfo() {
        return this.exception;
    }
}
