
package icreateshipsv.org.ufida;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.4.0
 * 2020-11-11T11:45:25.259+08:00
 * Generated source version: 3.4.0
 */

@WebFault(name = "ServiceExceptionDetail", targetNamespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF.Service")
public class UFIDAU9ISVSMICreateShipSVDoServiceExceptionDetailFaultFaultMessage extends Exception {

    private icreateshipsv.org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceExceptionDetail serviceExceptionDetail;

    public UFIDAU9ISVSMICreateShipSVDoServiceExceptionDetailFaultFaultMessage() {
        super();
    }

    public UFIDAU9ISVSMICreateShipSVDoServiceExceptionDetailFaultFaultMessage(String message) {
        super(message);
    }

    public UFIDAU9ISVSMICreateShipSVDoServiceExceptionDetailFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public UFIDAU9ISVSMICreateShipSVDoServiceExceptionDetailFaultFaultMessage(String message, icreateshipsv.org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceExceptionDetail serviceExceptionDetail) {
        super(message);
        this.serviceExceptionDetail = serviceExceptionDetail;
    }

    public UFIDAU9ISVSMICreateShipSVDoServiceExceptionDetailFaultFaultMessage(String message, icreateshipsv.org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceExceptionDetail serviceExceptionDetail, Throwable cause) {
        super(message, cause);
        this.serviceExceptionDetail = serviceExceptionDetail;
    }

    public icreateshipsv.org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceExceptionDetail getFaultInfo() {
        return this.serviceExceptionDetail;
    }
}
