
package icreateshipsv.org.ufida;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.4.0
 * 2020-11-11T11:45:25.107+08:00
 * Generated source version: 3.4.0
 */

@WebFault(name = "ServiceLostException", targetNamespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF.Service")
public class UFIDAU9ISVSMICreateShipSVDoServiceLostExceptionFaultFaultMessage extends Exception {

    private icreateshipsv.org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceLostException serviceLostException;

    public UFIDAU9ISVSMICreateShipSVDoServiceLostExceptionFaultFaultMessage() {
        super();
    }

    public UFIDAU9ISVSMICreateShipSVDoServiceLostExceptionFaultFaultMessage(String message) {
        super(message);
    }

    public UFIDAU9ISVSMICreateShipSVDoServiceLostExceptionFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public UFIDAU9ISVSMICreateShipSVDoServiceLostExceptionFaultFaultMessage(String message, icreateshipsv.org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceLostException serviceLostException) {
        super(message);
        this.serviceLostException = serviceLostException;
    }

    public UFIDAU9ISVSMICreateShipSVDoServiceLostExceptionFaultFaultMessage(String message, icreateshipsv.org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceLostException serviceLostException, Throwable cause) {
        super(message, cause);
        this.serviceLostException = serviceLostException;
    }

    public icreateshipsv.org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceLostException getFaultInfo() {
        return this.serviceLostException;
    }
}
