
package icreateshipsv.org.ufida;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.4.0
 * 2020-11-11T11:45:25.013+08:00
 * Generated source version: 3.4.0
 */

@WebFault(name = "ExceptionBase", targetNamespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF")
public class UFIDAU9ISVSMICreateShipSVDoExceptionBaseFaultFaultMessage extends Exception {

    private icreateshipsv.org.datacontract.schemas._2004._07.ufsoft.ExceptionBase exceptionBase;

    public UFIDAU9ISVSMICreateShipSVDoExceptionBaseFaultFaultMessage() {
        super();
    }

    public UFIDAU9ISVSMICreateShipSVDoExceptionBaseFaultFaultMessage(String message) {
        super(message);
    }

    public UFIDAU9ISVSMICreateShipSVDoExceptionBaseFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public UFIDAU9ISVSMICreateShipSVDoExceptionBaseFaultFaultMessage(String message, icreateshipsv.org.datacontract.schemas._2004._07.ufsoft.ExceptionBase exceptionBase) {
        super(message);
        this.exceptionBase = exceptionBase;
    }

    public UFIDAU9ISVSMICreateShipSVDoExceptionBaseFaultFaultMessage(String message, icreateshipsv.org.datacontract.schemas._2004._07.ufsoft.ExceptionBase exceptionBase, Throwable cause) {
        super(message, cause);
        this.exceptionBase = exceptionBase;
    }

    public icreateshipsv.org.datacontract.schemas._2004._07.ufsoft.ExceptionBase getFaultInfo() {
        return this.exceptionBase;
    }
}
