package icreateshipsv.org.ufida;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.0
 * 2020-11-11T11:45:25.266+08:00
 * Generated source version: 3.4.0
 *
 */
@WebService(targetNamespace = "http://www.UFIDA.org", name = "UFIDA.U9.ISV.SM.ICreateShipSV")
@XmlSeeAlso({icreateshipsv.org.datacontract.schemas._2004._07.ufsoft_ubf_pl.ObjectFactory.class, icreateshipsv.org.datacontract.schemas._2004._07.ufsoft_ubf_util.ObjectFactory.class, icreateshipsv.businessentity.business.ubf.ufsoft.ObjectFactory.class, icreateshipsv.org.datacontract.schemas._2004._07.system.ObjectFactory.class, icreateshipsv.data.util.ubf.ufsoft.ObjectFactory.class, icreateshipsv.com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, icreateshipsv.pl.ubf.ufsoft.ObjectFactory.class, icreateshipsv.org.datacontract.schemas._2004._07.ufsoft.ObjectFactory.class, icreateshipsv.com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class, ObjectFactory.class, icreateshipsv.org.datacontract.schemas._2004._07.ufsoft_ubf.ObjectFactory.class, icreateshipsv.exceptions.ubf.ufsoft.ObjectFactory.class, icreateshipsv.org.ufida.entitydata.ObjectFactory.class})
public interface UFIDAU9ISVSMICreateShipSV {

    @WebMethod(operationName = "Do", action = "http://www.UFIDA.org/UFIDA.U9.ISV.SM.ICreateShipSV/Do")
    @Action(input = "http://www.UFIDA.org/UFIDA.U9.ISV.SM.ICreateShipSV/Do", output = "http://www.UFIDA.org/UFIDA.U9.ISV.SM.ICreateShipSV/DoResponse", fault = {@FaultAction(className = UFIDAU9ISVSMICreateShipSVDoServiceExceptionFaultFaultMessage.class, value = "http://www.UFIDA.org/UFIDA.U9.ISV.SM.ICreateShipSV/DoServiceExceptionFault"), @FaultAction(className = UFIDAU9ISVSMICreateShipSVDoExceptionBaseFaultFaultMessage.class, value = "http://www.UFIDA.org/UFIDA.U9.ISV.SM.ICreateShipSV/DoExceptionBaseFault"), @FaultAction(className = UFIDAU9ISVSMICreateShipSVDoServiceLostExceptionFaultFaultMessage.class, value = "http://www.UFIDA.org/UFIDA.U9.ISV.SM.ICreateShipSV/DoServiceLostExceptionFault"), @FaultAction(className = UFIDAU9ISVSMICreateShipSVDoExceptionFaultFaultMessage.class, value = "http://www.UFIDA.org/UFIDA.U9.ISV.SM.ICreateShipSV/DoExceptionFault"), @FaultAction(className = UFIDAU9ISVSMICreateShipSVDoServiceExceptionDetailFaultFaultMessage.class, value = "http://www.UFIDA.org/UFIDA.U9.ISV.SM.ICreateShipSV/DoServiceExceptionDetailFault")})
    @RequestWrapper(localName = "Do", targetNamespace = "http://www.UFIDA.org", className = "org.ufida.Do")
    @ResponseWrapper(localName = "DoResponse", targetNamespace = "http://www.UFIDA.org", className = "org.ufida.DoResponse")
    public void _do(

        @WebParam(name = "context", targetNamespace = "http://www.UFIDA.org")
        Object context,
        @WebParam(name = "shipDTOs", targetNamespace = "http://www.UFIDA.org")
        icreateshipsv.org.ufida.entitydata.ArrayOfUFIDAU9ISVSMShipDTOForIndustryChainData shipDTOs,
        @WebParam(name = "isUpdateBarCode", targetNamespace = "http://www.UFIDA.org")
        Boolean isUpdateBarCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "DoResult", targetNamespace = "http://www.UFIDA.org")
        javax.xml.ws.Holder<icreateshipsv.org.ufida.entitydata.ArrayOfUFIDAU9ISVSMDocKeyDTOData> doResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "outMessages", targetNamespace = "http://www.UFIDA.org")
        javax.xml.ws.Holder<icreateshipsv.exceptions.ubf.ufsoft.ArrayOfMessageBase> outMessages
    ) throws UFIDAU9ISVSMICreateShipSVDoServiceExceptionFaultFaultMessage, UFIDAU9ISVSMICreateShipSVDoExceptionBaseFaultFaultMessage, UFIDAU9ISVSMICreateShipSVDoServiceLostExceptionFaultFaultMessage, UFIDAU9ISVSMICreateShipSVDoExceptionFaultFaultMessage, UFIDAU9ISVSMICreateShipSVDoServiceExceptionDetailFaultFaultMessage;
}
